name: Build and Push to VPS

on:
  push:
    branches:
      - main

env:
  NODE_ENV: production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'yarn'

    - run: NODE_ENV=development yarn --frozen-lockfile
    - run: yarn build
    - run: yarn --prod --frozen-lockfile
    - run: docker build -t snekpay:$(git rev-parse --short "$GITHUB_SHA") .
    - run: docker save -o image.tar snekpay:$(git rev-parse --short "$GITHUB_SHA")
    - uses: actions/upload-artifact@v3
      with:
        name: container.tar
        path: image.tar
