name: Build and Push to VPS

on:
  push:
    branches:
      - main

env:
  NODE_ENV: production

jobs:
  build:
    timeout-minutes: 3
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'yarn'

    - name: Build node app
      run: |
        NODE_ENV=development yarn --frozen-lockfile
        yarn build
        yarn --prod --frozen-lockfile
    - name: Build docker
      run: docker build -t snekpay:$(git rev-parse --short "$GITHUB_SHA") .
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push to Docker Hub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/snekpay/snekpay:$(git rev-parse --short "$GITHUB_SHA")
